site_name: Build Assistants
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - seach.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to dark mode
      primary: blue
      accent: blue
    - scheme: slate
      toggle:
       icon: material/toggle-switch
       name: Switch to light mode
      primary: white
      accent: blue

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/

copyright:  |
 &copy; 2025 <a href="https://www.jonathanscorey.com"  target="_blank" rel="noopener">Build Assistants</a>
